### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.0 and version-bump

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@bollwyvl : Could you please review and merge.

**Comment by sannykr** [comment]
@synapticarbors : Do I need to erase the word "License" from License? It seems conda-forge-linter doesn't like it.

**Comment by synapticarbors** [comment]
I believe so.

**Comment by sannykr** [comment]
@conda-forge/staged-recipes : This pull request has passed all checks, but maintainer has not merged it yet. Is it possible for you to add as a maintainer and merge it if everything looks okay?

**Comment by 183amir** [comment]
Did you ping the maintainer first instead?

**Comment by 183amir** [comment]
OK. I see that you have pinged the maintainer. To add yourself as a maintainer, you need to add your name (your github username) to the list of maintainers in `meta.yaml` in this pull request.
Also, not everybody on @conda-forge/staged-recipes has permission to merge this (like me). You need to ping @conda-forge/core for these kind of issues.

**Comment by sannykr** [comment]
@183amir : Thanks

**Comment by bollwyvl** [comment]
Looks good, sorry for the delay!

**Pull request merged**
